export const cssVariableConfig = [
    { key: '--dv-paneview-active-outline-color', text: '' },
    { key: '--dv-tabs-and-actions-container-font-size', text: '' },
    { key: '--dv-tabs-and-actions-container-height', text: '' },
    { key: '--dv-tab-close-icon', text: '' },
    { key: '--dv-drag-over-background-color', text: '' },
    { key: '--dv-drag-over-border-color', text: '' },
    { key: '--dv-tabs-container-scrollbar-color', text: '' },
    { key: '--dv-group-view-background-color', text: '' },
    { key: '--dv-tabs-and-actions-container-background-color', text: '' },
    { key: '--dv-activegroup-visiblepanel-tab-background-color', text: '' },
    { key: '--dv-activegroup-hiddenpanel-tab-background-color', text: '' },
    { key: '--dv-inactivegroup-visiblepanel-tab-background-color', text: '' },
    { key: '--dv-inactivegroup-hiddenpanel-tab-background-color', text: '' },
    { key: '--dv-tab-divider-color', text: '' },
    { key: '--dv-activegroup-visiblepanel-tab-color', text: '' },
    { key: '--dv-activegroup-hiddenpanel-tab-color', text: '' },
    { key: '--dv-inactivegroup-visiblepanel-tab-color', text: '' },
    { key: '--dv-inactivegroup-hiddenpanel-tab-color', text: '' },
    { key: '--dv-separator-border', text: '' },
    { key: '--dv-paneview-header-border-color', text: '' },
    { key: '--dv-icon-hover-background-color', text: '' },
    { key: '--dv-floating-box-shadow', text: '' },
    { key: '--dv-active-sash-color', text: '' },
    { key: '--dv-background-color', text: '' },
];
